name: arm64 R builds v2

on:
  workflow_dispatch:
    inputs:
      platforms:
        description: |
          Comma-separated list of platforms. Specify "all" to use all platforms (the default).
        required: false
        default: 'all'
        type: string
      r_versions:
        description: |
          Comma-separated list of R versions. Specify "last-N" to use the
          last N minor R versions, or "all" to use all minor R versions since R 3.1.
          Defaults to "last-5".
        required: false
        default: 'next,devel'
        type: string

permissions:
  contents: read

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      platforms: ${{ steps.setup-matrix.outputs.platforms }}
      r_versions: ${{ steps.setup-matrix.outputs.r_versions }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up matrix of platforms and R versions
      id: setup-matrix
      run: |
        platforms=$(python test/get_platforms.py ${{ github.event.inputs.platforms }})
        echo "platforms=$platforms" >> $GITHUB_OUTPUT
        r_versions=$(python test/get_r_versions.py ${{ github.event.inputs.r_versions || 'next,devel' }})
        echo "r_versions=$r_versions" >> $GITHUB_OUTPUT

  docker-images:
    needs: setup-matrix
    strategy:
      matrix:
        platform: ${{ fromJson(needs.setup-matrix.outputs.platforms) }}
    runs-on: macos-14
    name: Docker image (${{ matrix.platform }})
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v3

      - name: Build R
        run: |
          cd builder && docker compose up ${{ matrix.platform }}
        env:
          R_VERSION: ${{ matrix.r_version }}
          DOCKER_DEFAULT_PLATFORM: linux/arm64

      - name: Copy and rename package
        run: |
          pkg=$(find builder/integration -name "*.deb" -or -name "*.rpm")
          pkg2=$(echo $pkg | sed "s|/[rR]-|/r-rstudio-${{ matrix.platform }}-|")
          pkg2=$(basename "$pkg2")
          cp "$pkg" "$pkg2"
          ls -l .

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          repository: r-hub/R
          token: ${{ secrets.DEPLOY_TOKEN }}
          files: |
            *-rstudio-*.deb
            *-rstudio-*.rpm
          name: "R ${{ matrix.r_version }}"
          tag_name: v${{ matrix.r_version }}
